# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm test
    - name: Build Docker image
      run: docker build -t latihan_fastapi_app:latest .
    - name: Build Docker image
      run: docker tag latihan_fastapi_app registry.digitalocean.com/ariandigital/latihan_fastapi_app:latest
    - name: Log in to Docker registry
      run: echo ${{ secrets.DIGITALOCEAN_REGISTRY_PASSWORD }} | docker login registry.digitalocean.com/ariandigital --username ${{ secrets.DIGITALOCEAN_REGISTRY_USERNAME }} --password-stdin
    - name: Push Docker image
      run: docker push registry.digitalocean.com/ariandigital/latihan_fastapi_app:latest
    - name: SSH into Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          doctl registry garbage-collection start -f
          sudo docker pull registry.digitalocean.com/ariandigital/latihan_fastapi_app
          sudo docker rm --force latihan_fastapi
          sudo docker run -p 8000:8000 -d --name latihan_fastapi registry.digitalocean.com/ariandigital/latihan_fastapi_app:latest
