# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'
    # - run: npm install -g node-pre-gyp
    # - run: npm install
    # - name: Build Docker image
    #   run: docker build -t latihan_webrtc:latest .
    # - name: Build Docker image
    #   run: docker tag latihan_webrtc registry.digitalocean.com/ariandigital/latihan_webrtc:latest
    # - name: Log in to Docker registry
    #   run: echo ${{ secrets.DIGITALOCEAN_REGISTRY_PASSWORD }} | docker login registry.digitalocean.com/ariandigital --username ${{ secrets.DIGITALOCEAN_REGISTRY_USERNAME }} --password-stdin
    # - name: Push Docker image
    #   run: docker push registry.digitalocean.com/ariandigital/latihan_webrtc:latest
    # - name: SSH into Server
    #   uses: appleboy/ssh-action@master
    #   with:
    #     host: ${{ secrets.SERVER_HOST }}
    #     username: ${{ secrets.SERVER_USERNAME }}
    #     key: ${{ secrets.SSH_KEY }}
    #     script: |
    #       echo "hello"
    #       # doctl registry garbage-collection start -f
    #       # sudo docker pull registry.digitalocean.com/ariandigital/latihan_webrtc
    #       # sudo docker rm --force latihan_webrtc
    #       # sudo docker run -p 5000:5000 -d --name latihan_webrtc registry.digitalocean.com/ariandigital/latihan_webrtc:latest
